# Generated by Django 3.0.8 on 2021-01-07 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20210107_0206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'get_latest_by': 'pk', 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
    ]
