# Generated by Django 3.0.8 on 2021-01-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='letter.Letter')),
                ('senderName', models.CharField(max_length=100)),
                ('senderPhone', models.CharField(max_length=20)),
                ('senderFullAddress', models.CharField(max_length=200)),
                ('senderDetailedAddress', models.CharField(max_length=200)),
                ('senderZoneCode', models.IntegerField()),
                ('receiverName', models.CharField(max_length=100)),
                ('receiverPhone', models.CharField(max_length=20)),
                ('receiverFullAddress', models.CharField(max_length=200)),
                ('receiverDetailedAddress', models.CharField(max_length=200)),
                ('receiverZoneCode', models.IntegerField()),
                ('postMethod', models.CharField(choices=[('a', '일반우편'), ('b', '등기우편')], default='a', max_length=5)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.Customer')),
                ('letterName', models.CharField(max_length=100)),
                ('letterPrice', models.IntegerField()),
                ('page_price', models.IntegerField()),
                ('photo_price', models.IntegerField(default=0, null=True)),
                ('postMethod', models.CharField(default='a', max_length=20)),
                ('postMethod_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
    ]
