# Generated by Django 3.0.8 on 2020-12-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='letter.Letter')),
                ('senderName', models.CharField(max_length=30)),
                ('senderPhone', models.CharField(max_length=14)),
                ('senderAddr', models.CharField(max_length=30)),
                ('receiver', models.CharField(max_length=30)),
                ('receiverPhone', models.CharField(max_length=14)),
                ('receiverAddr', models.CharField(max_length=30)),
                ('send_mail', models.CharField(choices=[('regular', '일반우편'), ('registered', '등기우편')], default='regular', max_length=20)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.Customer')),
                ('letterName', models.CharField(max_length=100)),
                ('letterPrice', models.IntegerField()),
                ('letterPage_count', models.IntegerField()),
                ('photo_price', models.IntegerField(default=0, null=True)),
                ('send_mail', models.CharField(default='regular', max_length=20)),
                ('total_price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
    ]
